# Generated by Django 4.0.6 on 2023-02-07 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Left', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Right', to=settings.AUTH_USER_MODEL),
        ),
    ]
