# Generated by Django 4.0.6 on 2023-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0006_notification_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
