# Generated by Django 4.0.6 on 2023-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0007_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='videoId',
            field=models.IntegerField(default=6789),
        ),
    ]
