# Generated by Django 4.0.6 on 2023-01-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='image',
            field=models.ImageField(null=True, upload_to='Image/'),
        ),
    ]
