# Generated by Django 4.1.5 on 2023-01-09 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=255)),
                ('note1', models.CharField(max_length=255)),
                ('note2', models.CharField(max_length=255)),
                ('note3', models.CharField(max_length=255)),
                ('note4', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept', to='Doctor.departments')),
            ],
        ),
    ]
