# Generated by Django 4.1.5 on 2023-01-09 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0001_initial'),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctors',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working', to='Hospital.hospitals'),
        ),
    ]
