# Generated by Django 4.0.6 on 2023-01-10 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0004_alter_doctors_department_alter_doctors_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
