# Generated by Django 4.0.6 on 2023-01-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_alter_doctors_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(null=True, upload_to='BackEnd/Static/Images'),
        ),
    ]
