# Generated by Django 4.0.6 on 2023-01-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0006_doctors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='image',
            field=models.ImageField(null=True, upload_to='Image/'),
        ),
    ]
